spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ejappv2
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true